{
    'name': "Cricket Box Booking Management",
    'summary': "Cricket Box Booking Management System",
    'description': "This is Cricket Box Booking Management System",
    'author': "Vivek Vaghela",
    'version': '0.1',
    'sequence': -1,
    'depends': ['account', "website","mail","portal"],
    'data': [
        'security/cricket_box_booking_management_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/product_product_data.xml',
        'views/cricket_box_views.xml',
        'views/time_slots_views.xml',
        'views/cricket_box_registration_views.xml',
        'views/cricket_box_registration_report.xml',
        'report/cricket_box_registration_templates.xml',
        'views/cricket_box_menu.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
