
{
    'name': 'Hospital Management',
    'version': '1.2',
    'category': 'Hospital Management System',
    'sequence': 6,
    'summary': 'Hospital Management System ',
    'author': 'Vivek Vaghela ',
    'description': """ This module contains all the common features For Hospital Management System.  """,
    'depends': ['mail','product','base'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/cancel_appointment.xml',
        'data/patient_data.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        # 'views/appointment_view.xml',
        'views/female_patient_view.xml',
        'views/patient_tag_view.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'assets': {},
    'license': 'LGPL-3',
}
